version: '3'

services:
  redis:
    image: redis:5.0.7-alpine

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: bash -c "mkdir -p media/product && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A shop_project worker --loglevel=info -P eventlet
    volumes:
      - .:/app
    depends_on:
      - django

  flower:
    container_name: flower
    build:
      context: .
    ports:
      - 5555:5555
    command: celery -A shop_project flower
    volumes:
      - .:/app
    depends_on:
      - celery
