# Generated by Django 5.0.1 on 2024-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('rating_value', models.IntegerField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Rating',
                'ordering': ('-id',),
                'index_together': {('id', 'product_id')},
            },
        ),
    ]
