# Generated by Django 5.0.1 on 2024-02-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_password',
            field=models.CharField(max_length=256),
        ),
    ]
