# Generated by Django 5.0.1 on 2024-02-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_customuser_user_activated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
