# Generated by Django 5.0.1 on 2024-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('text_review', models.TextField(max_length=1000)),
                ('data_review', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
