# Generated by Django 5.0.1 on 2024-02-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addreview',
            options={'ordering': ('user_id',), 'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
    ]
